### ISSUE TITLE
IS THIS PROJECT DEAD?

### ISSUE THREAD

**Issue by timacdonald** [AndrewFeeney/all-positive-integers-in-ascending-order#8]

**Comment by adrianb93** [comment]
rip 💀

**Comment by AndrewFeeney** [comment]
I maintain this library of my own volition in my free time. In between my actual job commitments and family responsibilities I barely have time for basic care let alone keeping on top of the maintenance burden of this project. As such, even though I've got lots of ideas for integers I'd like to add, I rarely get a chance to put them together.

You're welcome to add a PR and I'll consider it.

Alternatively, if the company you work for uses this in production, you could consider getting them to sponsor a holiday to the Bahamas for me and my family, after which I might be more inclined to give this library the attention it deserves. I feel it's not unreasonable to ask.

**Comment by timacdonald** [comment]
I keep switching between laughing - but also knowing that this is also way to real 😆

**Comment by adrianb93** [comment]
Mate, fork and maintain your own version if you’re not happy with the
response. Keep up the good work Andrew 👏

**Comment by AndrewFeeney** [comment]
I'm closing this issue because it has not received any activity in almost one year. Please feel free to reopen if this issue is persisting, preferably with some replication steps for your issue.

**Comment by timacdonald** [comment]
Wow. Just wow.

**Comment by AndrewFeeney** [comment]
*hands on hips, shaking head*
