### ISSUE TITLE
Support for negative integers

### ISSUE THREAD

**Issue by davidgarywood** [AndrewFeeney/all-positive-integers-in-ascending-order#9]
Can we update this to support negative integers please? These numbers are necessary for my program to progress further

**Comment by AndrewFeeney** [comment]
Thanks for the question. I've given this some thought, and here's my thinking:

- I can see how some people might need a list of negative numbers, however not all users of the project will need these
- Including support for negative integers presents some issues, for instance:
-- Where will we keep them? Keeping them in the same file as the positive ones doesn't seem feasible as the lists will grow in opposite directions
--- Therefore we'd have to create a new file
--- What would we name it?
--- Would we then have to rename our existing file?
-- We would need to rewrite our CI tooling
-- This would double the time to complete the set
-- This would double the size of the project for those who wish to download it

For these reasons among others, I think the only reasonable decision is to reject this request on the basis that it represents significant scope creep. Listing all negative integers is just not the problem that this project has set out to solve. By ignoring problems outside the scope we can help ensure that we provide the best possible solution for the problems within the scope.

I thank you again for your time and effort. I'm going to close this issue, but if you wish to make further arguments feel free to reopen it.

**Comment by davidgarywood** [comment]
I understand, and although I appreciate your POV and arguments in favour of closing this issue, I just wanted to inform you I will have to fork and continue the project for my own needs. I hope in the future we can reconcile the projects' aims and direction to pool our efforts. Thank you.
